-- ============================================
-- MK LABS CONSOLE DATABASE
-- ============================================

-- 1. Developer profiles
create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    role text not null default 'developer'
        check (role in ('developer', 'admin')),
    created_at timestamptz not null default now()
);

-- 2. Attendance records
create table public.attendance (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    clock_in timestamptz not null default now(),
    clock_out timestamptz,
    created_at timestamptz not null default now(),

    check (clock_out is null or clock_out >= clock_in)
);

-- Only one active clock-in per developer
create unique index one_active_attendance_per_user
on public.attendance (user_id)
where clock_out is null;


-- ============================================
-- 3. AUTOMATIC PROFILE CREATION
-- ============================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin

    insert into public.profiles (id, full_name)
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'full_name',
            new.email
        )
    );

    return new;

end;
$$;


create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();


-- ============================================
-- 4. ADMIN CHECK FUNCTION
-- ============================================

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
        and role = 'admin'
    );
$$;


-- ============================================
-- 5. CLOCK IN
-- ============================================

create or replace function public.clock_in()
returns public.attendance
language plpgsql
security definer
set search_path = public
as $$
declare
    result public.attendance;
begin

    if auth.uid() is null then
        raise exception 'You must be logged in';
    end if;

    insert into public.attendance (user_id)
    values (auth.uid())
    returning * into result;

    return result;

exception
    when unique_violation then
        raise exception 'You are already clocked in';
end;
$$;


-- ============================================
-- 6. CLOCK OUT
-- ============================================

create or replace function public.clock_out()
returns public.attendance
language plpgsql
security definer
set search_path = public
as $$
declare
    result public.attendance;
begin

    if auth.uid() is null then
        raise exception 'You must be logged in';
    end if;

    update public.attendance
    set clock_out = now()
    where user_id = auth.uid()
      and clock_out is null
    returning * into result;

    if result.id is null then
        raise exception 'You are not currently clocked in';
    end if;

    return result;

end;
$$;


-- ============================================
-- 7. ENABLE ROW LEVEL SECURITY
-- ============================================

alter table public.profiles enable row level security;
alter table public.attendance enable row level security;


-- ============================================
-- 8. PROFILE SECURITY
-- ============================================

-- Developers can see their own profile
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (
    id = auth.uid()
);

-- Admins can see all profiles
create policy "Admins can view all profiles"
on public.profiles
for select
to authenticated
using (
    public.is_admin()
);


-- ============================================
-- 9. ATTENDANCE SECURITY
-- ============================================

-- Developers can see their own attendance
create policy "Users can view own attendance"
on public.attendance
for select
to authenticated
using (
    user_id = auth.uid()
);

-- Admins can see all attendance
create policy "Admins can view all attendance"
on public.attendance
for select
to authenticated
using (
    public.is_admin()
);


-- ============================================
-- 10. WORKING HOURS VIEW
-- ============================================

create or replace view public.attendance_summary
with (security_invoker = true)
as
select
    a.id,
    a.user_id,
    p.full_name,
    p.role,
    a.clock_in,
    a.clock_out,

    case
        when a.clock_out is not null
        then extract(epoch from (a.clock_out - a.clock_in))
        else extract(epoch from (now() - a.clock_in))
    end as working_seconds

from public.attendance a
join public.profiles p
    on p.id = a.user_id;


-- ============================================
-- 11. FUNCTION PERMISSIONS
-- ============================================

grant execute on function public.clock_in() to authenticated;
grant execute on function public.clock_out() to authenticated;

grant execute on function public.is_admin() to authenticated;